var1 = int(input("Enter number 1\n"))
var2 = int(input("Enter number 2\n"))
print("There are a total of 6 comparison operators in python...\n")
print(f"The '==' operator checks if the variables are equal if yes returns 'True' {var1}=={var2} = {var1==var2}\n")
print(f"The '>' operator checks if the variable is greater than the other if yes returns 'True' {var1}>{var2} = {var1>var2}\n")
print(f"The '<' operator checks if the variable is smaller than the other if yes returns 'True' {var1}<{var2} = {var1<var2}\n")
print(f"The '>=' operator checks if the variable is greater than or equals to the other if yes returns 'True' {var1}>={var2} = {var1>=var2}\n")
print(f"The '<=' operator checks if the variable is smaller than or equals to the other if yes returns 'True' {var1}<={var2} = {var1<=var2}\n")
print(f"The '!=' operator checks if the variable is not equal to the other if yes returns 'True' {var1}!={var2} = {var1!=var2}\n")